/**
 * Personalization: what a page shows, in what order, and under what label.
 *
 * The boundary this module sits on is the same one phase 10 drew for journals and phase 13 drew for
 * sharing, and it runs one way:
 *
 *   **A preference decides what is displayed. It can never decide what is calculated.**
 *
 * There is no figure in this file. A widget is an id and a position; a metric is a *pointer* to a
 * number the analytics engine already computed; a saved view is a filter and a sort. Delete every
 * preference a user has and their holdings, cost basis and P&L are byte-identical —
 * `personalization-boundary.test.ts` asserts exactly that, and reads this file's source to keep it
 * free of anything that could reach a database or a network.
 *
 * Pure: no React, no Supabase, no fetch, no framework import.
 */

// ---------------------------------------------------------------- display preferences

export const THEMES = ["system", "light", "dark"] as const
export type Theme = (typeof THEMES)[number]

/**
 * How tightly a table packs.
 *
 * Two options, not five. "Comfortable" and "compact" are a real choice somebody makes once;
 * anything more is a slider nobody moves, and every extra value is another set of paddings to keep
 * consistent across four tables.
 */
export const DENSITIES = ["comfortable", "compact"] as const
export type Density = (typeof DENSITIES)[number]

export const DENSITY_LABELS: Record<Density, string> = {
  comfortable: "Comfortable",
  compact: "Compact",
}

/** Row padding classes, in one place, so the four tables that honour density cannot drift apart. */
export const DENSITY_CLASSES: Record<Density, { row: string; cell: string }> = {
  comfortable: { row: "py-3", cell: "px-3 py-3" },
  compact: { row: "py-1.5", cell: "px-2 py-1.5" },
}

// ---------------------------------------------------------------- widgets

/**
 * Every widget the dashboard can show.
 *
 * Each one is a **section that already existed** on the dashboard before this phase, given an id so
 * it can be ordered and hidden. Nothing here computes anything: the widget is the arrangement, and
 * the figures inside it come from the same single `loadIntelligence` pass the page always made.
 * That is what keeps ten widgets from becoming ten requests.
 */
export const WIDGETS = [
  "summary",
  "quickActions",
  "performance",
  "allocation",
  "movers",
  "goals",
  "insights",
  "dividends",
  "alerts",
  "transactions",
  "watchlist",
  "pinned",
  "recent",
  "dataQuality",
  "attribution",
  "drawdowns",
  "events",
  "news",
] as const
export type WidgetId = (typeof WIDGETS)[number]

export type WidgetDefinition = {
  id: WidgetId
  label: string
  description: string
  /** A widget the user cannot hide, because a dashboard without it is not a dashboard. */
  required?: boolean
  /** Spans the full width of the grid rather than half. */
  wide?: boolean
}

export const WIDGET_REGISTRY: Record<WidgetId, WidgetDefinition> = {
  summary: {
    id: "summary",
    label: "Portfolio summary",
    description: "Value, total return, today's change and position count.",
    // The one widget that cannot be switched off. Everything else on the page is context for it.
    required: true,
    wide: true,
  },
  quickActions: {
    id: "quickActions",
    label: "Quick actions",
    description: "Record a transaction, a dividend or a cash movement.",
    wide: true,
  },
  performance: { id: "performance", label: "Performance", description: "Time-weighted return over the selected period." },
  allocation: { id: "allocation", label: "Allocation", description: "How the portfolio is divided, by position, market or tag." },
  movers: { id: "movers", label: "Top movers", description: "Largest gains and losses among your positions." },
  goals: { id: "goals", label: "Goal progress", description: "Progress towards the targets you set." },
  insights: { id: "insights", label: "Observations", description: "Facts about this portfolio, generated by rules." },
  dividends: { id: "dividends", label: "Dividends", description: "Income received and yield on cost." },
  alerts: { id: "alerts", label: "Active alerts", description: "Alerts currently armed." },
  transactions: { id: "transactions", label: "Recent transactions", description: "The last few things you recorded." },
  watchlist: { id: "watchlist", label: "Watchlist", description: "Symbols you are following but do not hold." },
  pinned: { id: "pinned", label: "Pinned", description: "Whatever you pinned for quick access." },
  recent: { id: "recent", label: "Recently viewed", description: "The last stocks and portfolios you opened." },
  dataQuality: { id: "dataQuality", label: "Data quality", description: "Stale prices, missing rates and unresolved imports." },
  attribution: {
    id: "attribution",
    label: "Top contributors",
    description: "Which holdings added most to the portfolio's return, and which removed most.",
    wide: true,
  },
  events: {
    id: "events",
    label: "Upcoming events",
    description: "Earnings and dividend dates for the instruments you hold or watch.",
    wide: true,
  },
  news: {
    id: "news",
    label: "News",
    description: "Recent coverage of the instruments you hold and watch.",
    wide: true,
  },
  drawdowns: {
    id: "drawdowns",
    label: "Drawdowns",
    description: "How far the portfolio has fallen from its high, and whether it recovered.",
  },
}

export type WidgetPlacement = {
  id: WidgetId
  visible: boolean
}

/**
 * What a new user sees, and what "Reset" restores.
 *
 * Chosen so the page answers the three questions somebody opens a portfolio tracker to ask — what
 * is it worth, how is it doing, what is it made of — before anything else. A dashboard that starts
 * empty and asks to be configured is a dashboard nobody configures.
 */
export const DEFAULT_LAYOUT: readonly WidgetPlacement[] = [
  { id: "summary", visible: true },
  { id: "quickActions", visible: true },
  { id: "performance", visible: true },
  { id: "allocation", visible: true },
  { id: "movers", visible: true },
  { id: "goals", visible: true },
  { id: "insights", visible: true },
  { id: "transactions", visible: true },
  { id: "watchlist", visible: true },
  { id: "alerts", visible: false },
  { id: "dividends", visible: false },
  { id: "pinned", visible: false },
  { id: "recent", visible: false },
  { id: "dataQuality", visible: false },
  // Phase 16: available, off by default. A new widget must never rearrange an existing dashboard.
  { id: "attribution", visible: false },
  { id: "drawdowns", visible: false },
  { id: "events", visible: false },
  { id: "news", visible: false },
]

/**
 * Reconciles a stored layout with the registry.
 *
 * Three things can be wrong with a layout read from the database, and all three are normal rather
 * than exceptional: a widget was **added** in a release after it was saved, a widget was
 * **removed**, or the row is empty because the user has never customised anything. So this is not
 * validation — it is the function that makes a stored layout mean something under a registry that
 * has since changed.
 *
 * A widget the user has never seen is appended in its default visibility, never silently switched
 * on at the top where it would displace what they arranged.
 */
export function resolveLayout(stored: readonly WidgetPlacement[] | null | undefined): WidgetPlacement[] {
  if (!stored || stored.length === 0) return DEFAULT_LAYOUT.map((w) => ({ ...w }))

  const known = new Set<WidgetId>()
  const resolved: WidgetPlacement[] = []

  for (const placement of stored) {
    // A widget that no longer exists is dropped rather than rendered as a blank card.
    if (!(placement.id in WIDGET_REGISTRY) || known.has(placement.id)) continue
    known.add(placement.id)
    resolved.push({
      id: placement.id,
      // A required widget is visible whatever the stored row says — including a row written before
      // it became required.
      visible: WIDGET_REGISTRY[placement.id].required ? true : placement.visible,
    })
  }

  for (const fallback of DEFAULT_LAYOUT) {
    if (!known.has(fallback.id)) resolved.push({ ...fallback })
  }

  return resolved
}

/** The widgets to render, in order. */
export function visibleWidgets(layout: readonly WidgetPlacement[]): WidgetId[] {
  return layout.filter((w) => w.visible).map((w) => w.id)
}

export function toggleWidget(
  layout: readonly WidgetPlacement[],
  id: WidgetId,
  visible: boolean,
): WidgetPlacement[] {
  return layout.map((w) =>
    // Hiding a required widget is a no-op rather than an error: the control is not offered, and a
    // request that asks anyway simply does not change anything.
    w.id === id && !WIDGET_REGISTRY[id].required ? { ...w, visible } : { ...w },
  )
}

/**
 * Moves a widget one place up or down.
 *
 * The keyboard- and touch-accessible half of reordering, and the only half that is *required*:
 * drag-and-drop is an enhancement on a pointer device, but "move up" works with a keyboard, with a
 * screen reader and with a thumb. See `docs/personalization.md`.
 */
export function moveWidget(
  layout: readonly WidgetPlacement[],
  id: WidgetId,
  direction: "up" | "down",
): WidgetPlacement[] {
  const index = layout.findIndex((w) => w.id === id)
  if (index === -1) return layout.map((w) => ({ ...w }))

  const target = direction === "up" ? index - 1 : index + 1
  if (target < 0 || target >= layout.length) return layout.map((w) => ({ ...w }))

  const next = layout.map((w) => ({ ...w }))
  ;[next[index], next[target]] = [next[target], next[index]]
  return next
}

/** Reorders to an explicit sequence — what a drag-and-drop gesture produces. */
export function reorderWidgets(
  layout: readonly WidgetPlacement[],
  order: readonly WidgetId[],
): WidgetPlacement[] {
  const byId = new Map(layout.map((w) => [w.id, w]))
  const next: WidgetPlacement[] = []
  for (const id of order) {
    const found = byId.get(id)
    if (found && !next.some((w) => w.id === id)) {
      next.push({ ...found })
      byId.delete(id)
    }
  }
  // Anything the caller did not mention keeps its relative order at the end, so a partial order is
  // a safe request rather than a way to lose widgets.
  for (const remaining of layout) if (byId.has(remaining.id)) next.push({ ...remaining })
  return next
}

// ---------------------------------------------------------------- metrics

/**
 * The metrics a user can mark as favourites.
 *
 * Every id here **points at a figure the analytics engine already produces**. None is computed in
 * this module, and adding one means finding the existing field, not writing a formula.
 *
 * The names are deliberately unambiguous. There is no "Profit", no bare "Return" and no bare
 * "Yield" — each of those is two different numbers in a portfolio tracker, and a dashboard tile
 * that does not say which one it means is worse than no tile.
 */
export const METRICS = [
  "totalValue",
  "investedCapital",
  "totalReturnPct",
  "todayChange",
  "unrealizedPnl",
  "realizedPnl",
  "dividendIncome",
  "yieldOnCost",
  "yieldOnValue",
  "cashBalance",
  "cashRatio",
  "largestPositionWeight",
  "positionCount",
] as const
export type MetricId = (typeof METRICS)[number]

export type MetricDefinition = {
  id: MetricId
  label: string
  /** What the number actually is, in one sentence. Shown wherever the metric is chosen. */
  definition: string
  unit: "money" | "percent" | "count"
}

export const METRIC_REGISTRY: Record<MetricId, MetricDefinition> = {
  totalValue: {
    id: "totalValue",
    label: "Portfolio value",
    definition: "Market value of open positions plus cash, in the portfolio's base currency.",
    unit: "money",
  },
  investedCapital: {
    id: "investedCapital",
    label: "Invested capital",
    definition: "Cost basis of the shares currently held, buy fees included. Not money deposited.",
    unit: "money",
  },
  totalReturnPct: {
    id: "totalReturnPct",
    label: "Total return",
    definition: "Unrealised gain or loss as a percentage of the invested capital of open positions.",
    unit: "percent",
  },
  todayChange: {
    id: "todayChange",
    label: "Today's change",
    definition: "Change since the previous close, over the holdings that have one. N/A otherwise.",
    unit: "percent",
  },
  unrealizedPnl: {
    id: "unrealizedPnl",
    label: "Unrealised P&L",
    definition: "Market value minus cost basis for shares still held. Nothing has been booked.",
    unit: "money",
  },
  realizedPnl: {
    id: "realizedPnl",
    label: "Realised P&L",
    definition: "Profit and loss booked by shares already sold, fees on both sides included.",
    unit: "money",
  },
  dividendIncome: {
    id: "dividendIncome",
    label: "Dividend income",
    definition: "Net dividends received in the last 365 days.",
    unit: "money",
  },
  yieldOnCost: {
    id: "yieldOnCost",
    label: "Yield on cost",
    definition: "Trailing twelve-month dividends divided by what the shares cost.",
    unit: "percent",
  },
  yieldOnValue: {
    id: "yieldOnValue",
    label: "Yield on current value",
    definition: "Trailing twelve-month dividends divided by what the shares are worth today.",
    unit: "percent",
  },
  cashBalance: {
    id: "cashBalance",
    label: "Cash balance",
    definition: "Deposits minus withdrawals, adjusted for trades and dividends.",
    unit: "money",
  },
  cashRatio: {
    id: "cashRatio",
    label: "Cash ratio",
    definition: "Cash as a percentage of total portfolio value.",
    unit: "percent",
  },
  largestPositionWeight: {
    id: "largestPositionWeight",
    label: "Largest position",
    definition: "The biggest single holding's share of total portfolio value.",
    unit: "percent",
  },
  positionCount: {
    id: "positionCount",
    label: "Positions",
    definition: "How many instruments are currently held.",
    unit: "count",
  },
}

/** What the summary widget shows when the user has chosen nothing. */
export const DEFAULT_METRICS: readonly MetricId[] = [
  "totalValue",
  "totalReturnPct",
  "todayChange",
  "unrealizedPnl",
]

/** The most tiles the summary will render. Beyond six it stops being a summary. */
export const MAX_FAVORITE_METRICS = 6

export function toggleMetric(
  current: readonly MetricId[],
  id: MetricId,
): { metrics: MetricId[]; rejected: "LIMIT" | null } {
  if (current.includes(id)) return { metrics: current.filter((m) => m !== id), rejected: null }
  if (current.length >= MAX_FAVORITE_METRICS) return { metrics: [...current], rejected: "LIMIT" }
  return { metrics: [...current, id], rejected: null }
}

/** Falls back rather than rendering nothing: an empty choice means the user has not made one. */
export function resolveMetrics(stored: readonly MetricId[] | null | undefined): MetricId[] {
  const known = (stored ?? []).filter((m): m is MetricId => m in METRIC_REGISTRY)
  return known.length > 0 ? known.slice(0, MAX_FAVORITE_METRICS) : [...DEFAULT_METRICS]
}

// ---------------------------------------------------------------- saved views

export const VIEW_COLUMNS = [
  "symbol",
  "market",
  "quantity",
  "averageCost",
  "currentPrice",
  "marketValue",
  "weight",
  "unrealizedPnl",
  "returnPct",
  "todayReturnPct",
  "dividendIncome",
  "tags",
] as const
export type ViewColumn = (typeof VIEW_COLUMNS)[number]

export const COLUMN_LABELS: Record<ViewColumn, string> = {
  symbol: "Symbol",
  market: "Market",
  quantity: "Quantity",
  averageCost: "Average cost",
  currentPrice: "Price",
  marketValue: "Market value",
  weight: "Weight",
  unrealizedPnl: "Unrealised P&L",
  returnPct: "Return",
  todayReturnPct: "Today",
  dividendIncome: "Dividend income",
  tags: "Tags",
}

/**
 * Columns that carry a position's size in money.
 *
 * Named here so the *one* place that needs to know — a view whose owner wants composition without
 * amounts — asks a function rather than restating a list.
 */
export const MONEY_COLUMNS: readonly ViewColumn[] = [
  "averageCost",
  "currentPrice",
  "marketValue",
  "unrealizedPnl",
  "dividendIncome",
]

export const DEFAULT_COLUMNS: readonly ViewColumn[] = [
  "symbol",
  "quantity",
  "marketValue",
  "weight",
  "unrealizedPnl",
  "returnPct",
]

export const GROUPINGS = ["none", "tag", "market", "sector"] as const
export type Grouping = (typeof GROUPINGS)[number]

export const GROUPING_LABELS: Record<Grouping, string> = {
  none: "No grouping",
  tag: "Tag",
  market: "Market",
  sector: "Sector",
}

export const SORT_DIRECTIONS = ["asc", "desc"] as const
export type SortDirection = (typeof SORT_DIRECTIONS)[number]

/**
 * A filter is a closed triple, never an expression.
 *
 * Same rule as the screener's: a string the server interprets is a query language, and a query
 * language a client can write is an injection surface. Adding a filter means adding a member to
 * these enums and a case to `matchesViewFilter`.
 */
export const VIEW_FILTER_FIELDS = ["tag", "market", "weight", "returnPct", "unrealizedPnl"] as const
export type ViewFilterField = (typeof VIEW_FILTER_FIELDS)[number]

export const VIEW_FILTER_OPERATORS = ["is", "isNot", "gt", "lt"] as const
export type ViewFilterOperator = (typeof VIEW_FILTER_OPERATORS)[number]

export type ViewFilter = {
  field: ViewFilterField
  operator: ViewFilterOperator
  value: string | number
}

export type ViewConfig = {
  filters: ViewFilter[]
  sortBy: ViewColumn
  sortDirection: SortDirection
  columns: ViewColumn[]
  groupBy: Grouping
}

export const DEFAULT_VIEW_CONFIG: ViewConfig = {
  filters: [],
  sortBy: "marketValue",
  sortDirection: "desc",
  columns: [...DEFAULT_COLUMNS],
  groupBy: "none",
}

/** What a view is applied to. Deliberately narrow: no cost basis, no transaction, no note. */
export type ViewRow = {
  symbol: string
  market: string
  quantity: number
  marketValue: number | null
  weight: number | null
  unrealizedPnl: number
  returnPct: number
  sector: string | null
  tags: readonly string[]
}

/**
 * Whether one row passes one filter.
 *
 * The numeric comparisons return **false for a null**, which is the important case: a holding whose
 * weight could not be computed because no exchange rate reached the base currency is not "a holding
 * with a weight of zero". It is excluded from a `weight > 10` filter and from a `weight < 10` one,
 * because the honest answer to both is that it is unknown.
 */
export function matchesViewFilter(row: ViewRow, filter: ViewFilter): boolean {
  switch (filter.field) {
    case "tag": {
      const wanted = String(filter.value).toLowerCase()
      const has = row.tags.some((tag) => tag.toLowerCase() === wanted)
      return filter.operator === "isNot" ? !has : has
    }
    case "market": {
      const matches = row.market === String(filter.value)
      return filter.operator === "isNot" ? !matches : matches
    }
    case "weight":
      return compare(row.weight, filter)
    case "returnPct":
      return compare(row.returnPct, filter)
    case "unrealizedPnl":
      return compare(row.unrealizedPnl, filter)
  }
}

function compare(value: number | null, filter: ViewFilter): boolean {
  if (value === null || !Number.isFinite(value)) return false
  const target = Number(filter.value)
  if (!Number.isFinite(target)) return false
  switch (filter.operator) {
    case "gt":
      return value > target
    case "lt":
      return value < target
    case "is":
      return value === target
    case "isNot":
      return value !== target
  }
}

/**
 * Applies a saved view to a set of rows: filter, then sort, then group.
 *
 * Pure and total — it reorders and partitions rows and never alters one. A row's `marketValue` is
 * the same object property it was before; a view cannot change a number, only decide whether it is
 * on screen.
 */
export function applyView(
  rows: readonly ViewRow[],
  config: ViewConfig,
): { groups: { key: string; label: string; rows: ViewRow[] }[]; total: number } {
  const filtered = rows.filter((row) => config.filters.every((filter) => matchesViewFilter(row, filter)))
  const sorted = [...filtered].sort((a, b) => compareRows(a, b, config))

  if (config.groupBy === "none") {
    return { groups: [{ key: "all", label: "All holdings", rows: sorted }], total: sorted.length }
  }

  const buckets = new Map<string, ViewRow[]>()
  for (const row of sorted) {
    for (const key of groupKeys(row, config.groupBy)) {
      const bucket = buckets.get(key)
      if (bucket) bucket.push(row)
      else buckets.set(key, [row])
    }
  }

  const groups = [...buckets.entries()]
    .map(([key, groupRows]) => ({ key, label: key, rows: groupRows }))
    // "Ungrouped" always last, whatever it sorts as alphabetically: it is the residue, not a group.
    .sort((a, b) =>
      a.key === UNGROUPED ? 1 : b.key === UNGROUPED ? -1 : a.key.localeCompare(b.key),
    )

  return { groups, total: sorted.length }
}

/** The bucket for a row that the grouping cannot place. Never omitted, never guessed at. */
export const UNGROUPED = "Ungrouped"

/**
 * A row can belong to several groups when grouping by tag — a position tagged "Growth" and "Core"
 * appears under both, which is what a tag means. Every other grouping yields exactly one key.
 */
function groupKeys(row: ViewRow, grouping: Grouping): string[] {
  switch (grouping) {
    case "none":
      return ["all"]
    case "market":
      return [row.market]
    case "sector":
      // Never inferred from the symbol. A provider that returned no sector means the sector is
      // unknown, and saying so is the only honest option.
      return [row.sector ?? UNGROUPED]
    case "tag":
      return row.tags.length > 0 ? [...row.tags] : [UNGROUPED]
  }
}

function compareRows(a: ViewRow, b: ViewRow, config: ViewConfig): number {
  const direction = config.sortDirection === "asc" ? 1 : -1
  const left = sortValue(a, config.sortBy)
  const right = sortValue(b, config.sortBy)

  // Nulls sort last in both directions. A holding with no computable weight has not got the
  // smallest weight — it has an unknown one, and burying it at the bottom is less misleading than
  // putting it at either extreme.
  if (left === null && right === null) return a.symbol.localeCompare(b.symbol)
  if (left === null) return 1
  if (right === null) return -1

  if (typeof left === "string" && typeof right === "string") {
    return left.localeCompare(right) * direction
  }
  return ((left as number) - (right as number)) * direction
}

function sortValue(row: ViewRow, column: ViewColumn): string | number | null {
  switch (column) {
    case "symbol":
      return row.symbol
    case "market":
      return row.market
    case "quantity":
      return row.quantity
    case "marketValue":
      return row.marketValue
    case "weight":
      return row.weight
    case "unrealizedPnl":
      return row.unrealizedPnl
    case "returnPct":
      return row.returnPct
    // Columns a view can display but not sort by yet. Falls back to the symbol rather than
    // producing an arbitrary order that looks meaningful.
    default:
      return row.symbol
  }
}

// ---------------------------------------------------------------- pinned and recent

export const PINNABLE_KINDS = ["stock", "portfolio", "view", "goal", "screen"] as const
export type PinnableKind = (typeof PINNABLE_KINDS)[number]

export type PinnedItem = {
  kind: PinnableKind
  /** A symbol key, a uuid — whatever addresses the thing. Never a figure. */
  ref: string
  label: string
}

export const MAX_PINNED = 12
export const MAX_RECENT = 8

export function togglePin(
  current: readonly PinnedItem[],
  item: PinnedItem,
): { items: PinnedItem[]; rejected: "LIMIT" | null } {
  const existing = current.findIndex((p) => p.kind === item.kind && p.ref === item.ref)
  if (existing !== -1) return { items: current.filter((_, i) => i !== existing), rejected: null }
  if (current.length >= MAX_PINNED) return { items: [...current], rejected: "LIMIT" }
  return { items: [...current, item], rejected: null }
}

export function isPinned(current: readonly PinnedItem[], kind: PinnableKind, ref: string): boolean {
  return current.some((p) => p.kind === kind && p.ref === ref)
}

/**
 * Most recent first, deduplicated, bounded.
 *
 * A bounded list rather than a history: eight entries is enough to get back to what you were just
 * looking at, and it is deliberately too short to reconstruct what somebody has been researching.
 * See the privacy note in `docs/personalization.md`.
 */
export function recordRecent(
  current: readonly PinnedItem[],
  item: PinnedItem,
  max = MAX_RECENT,
): PinnedItem[] {
  const withoutDuplicate = current.filter((p) => !(p.kind === item.kind && p.ref === item.ref))
  return [item, ...withoutDuplicate].slice(0, max)
}

// ---------------------------------------------------------------- insight dismissal

/**
 * Insights a user has chosen not to see again, by rule code.
 *
 * By **code**, not by rendered sentence: dismissing "your largest position is 24.5%" should not
 * bring the same observation back tomorrow at 24.6%.
 */
export const MAX_DISMISSED_INSIGHTS = 40

/**
 * Rules that cannot be dismissed.
 *
 * These describe a state of the *data* rather than a state of the portfolio — stale prices, a
 * missing exchange rate — and hiding one means hiding the reason a figure on the same screen is
 * wrong. A user can dismiss an observation about their concentration; they cannot dismiss the
 * notice explaining why a total excludes a holding.
 */
export const UNDISMISSABLE_INSIGHTS: readonly string[] = [
  "DATA_STALE_PRICES",
  "DATA_QUOTE_AGE",
  "DATA_MISSING_FX",
  "DATA_UNTRANSLATED",
]

export function canDismiss(code: string): boolean {
  return !UNDISMISSABLE_INSIGHTS.includes(code)
}

export function dismissInsight(current: readonly string[], code: string): string[] {
  if (!canDismiss(code) || current.includes(code)) return [...current]
  return [...current, code].slice(-MAX_DISMISSED_INSIGHTS)
}

export function restoreInsight(current: readonly string[], code: string): string[] {
  return current.filter((c) => c !== code)
}

/** Filters a rendered insight list. Never removes an undismissable one, whatever is stored. */
export function withoutDismissed<T extends { code: string }>(
  insights: readonly T[],
  dismissed: readonly string[],
): T[] {
  return insights.filter((insight) => canDismiss(insight.code) === false || !dismissed.includes(insight.code))
}
