-- Phase 7: AI research assistant — conversations, messages and a usage/audit ledger.
--
-- Three tables and no more. There is no table for prompts, no table for cached answers and no
-- table for "AI insights": an answer is a message, and a cached answer is a message that already
-- exists. Anything the AI says about a number is re-derived from the tables that own that number.

-- ---------------------------------------------------------------- conversations

create table public.ai_conversations (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  -- Taken from the first question, trimmed. Never generated by a second model call: a title is
  -- not worth an API round trip.
  title      text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint ai_conversations_title_length check (length(btrim(title)) between 1 and 120)
);

create index ai_conversations_user_idx on public.ai_conversations (user_id, updated_at desc);

create trigger ai_conversations_touch_updated_at
  before update on public.ai_conversations
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- messages
--
-- `content` is the prose. `data` is the structured payload the UI renders as cards — the grounded
-- figures, which were computed by Stockly and merely described by the model. Storing both means a
-- reopened conversation shows exactly what the user saw, without re-running anything.

create table public.ai_messages (
  id              uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.ai_conversations (id) on delete cascade,
  user_id         uuid not null references auth.users (id) on delete cascade,
  role            text not null,
  content         text not null,
  data            jsonb,
  intent          text,
  symbols         text[] not null default '{}',
  created_at      timestamptz not null default now(),

  constraint ai_messages_role_known check (role in ('user', 'assistant')),
  -- A hard ceiling in the database as well as in Zod: an unbounded text column is an easy way to
  -- make somebody else's storage bill your problem.
  constraint ai_messages_content_length check (length(content) between 1 and 20000)
);

create index ai_messages_conversation_idx on public.ai_messages (conversation_id, created_at);

-- ---------------------------------------------------------------- usage and audit ledger
--
-- One table, not two. Cost control, rate limiting and the audit trail all want the same row:
-- who asked, what kind of question, which model, how many tokens, how long, did it work. Splitting
-- them would mean writing twice and reconciling later.
--
-- **The prompt is not stored.** `symbols` and `intent` say what the request was about, which is
-- what an audit needs; the question text itself lives in ai_messages, where the user can delete it.

create table public.ai_usage (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  provider       text not null,
  model          text not null,
  intent         text,
  symbols        text[] not null default '{}',
  input_tokens   integer not null default 0,
  output_tokens  integer not null default 0,
  -- Estimated from a per-model rate table in the application, so a price change does not require
  -- rewriting history. Null when the model is not in that table.
  estimated_cost numeric(12, 6),
  latency_ms     integer,
  status         text not null,
  -- A stable error code, never provider text: provider messages can echo the prompt back.
  error_code     text,
  created_at     timestamptz not null default now(),

  constraint ai_usage_status_known check (status in ('ok', 'error')),
  constraint ai_usage_tokens_nonnegative check (input_tokens >= 0 and output_tokens >= 0)
);

-- The daily quota counts rows in a rolling 24-hour window for one user; this index is what makes
-- that a lookup rather than a scan.
create index ai_usage_user_time_idx on public.ai_usage (user_id, created_at desc);
-- Retention sweeps delete by age across every user.
create index ai_usage_created_idx on public.ai_usage (created_at);

-- ---------------------------------------------------------------- RLS
--
-- Everything here is user data. Default-deny, explicit policies, and the user_id is denormalised
-- onto ai_messages so a policy is a single-column check with no join — the same rule as every
-- other user table in this schema.

alter table public.ai_conversations enable row level security;
alter table public.ai_messages      enable row level security;
alter table public.ai_usage         enable row level security;

create policy "ai conversations are self-readable"   on public.ai_conversations
  for select using ((select auth.uid()) = user_id);
create policy "ai conversations are self-insertable" on public.ai_conversations
  for insert with check ((select auth.uid()) = user_id);
create policy "ai conversations are self-updatable"  on public.ai_conversations
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "ai conversations are self-deletable"  on public.ai_conversations
  for delete using ((select auth.uid()) = user_id);

create policy "ai messages are self-readable"   on public.ai_messages
  for select using ((select auth.uid()) = user_id);
create policy "ai messages are self-insertable" on public.ai_messages
  for insert with check ((select auth.uid()) = user_id);
create policy "ai messages are self-deletable"  on public.ai_messages
  for delete using ((select auth.uid()) = user_id);

-- Usage is readable and appendable by its owner, and never updatable or deletable by them: a
-- ledger a user can edit is not a ledger. Retention deletion runs under the service role.
create policy "ai usage is self-readable"   on public.ai_usage
  for select using ((select auth.uid()) = user_id);
create policy "ai usage is self-insertable" on public.ai_usage
  for insert with check ((select auth.uid()) = user_id);
